### ISSUE TITLE
Issue on page /content/04/01_Intro_to_scraping.html

### ISSUE THREAD

**Issue by jonathangaltathan** [LeDataSciFi/ledatascifi-2021#12]
I found a problem with this page under 4.1.2.. Specifically, the link in the third dropdown box (titled Install and Play) doesn't lead to a valid link on GitHub

**Comment by donbowen** [comment]
Let's get you maximum credit: go back to the page. Underneith "open issue" click suggest edit.

Then find that link in the page and replace it with this: https://ledatascifi.github.io/studentresourcevert/resource-landing.html#getting-data-and-practicing-ml

Then submit. I'll accept, and you'll have submitted your first pull request!
